ktor {
  deployment {
    port = ${?PORT}
    host = ${?HOST}
  }
  application {
    modules = [ org.example.project.ApplicationKt.module ]
  }
  environment = ${?ENV}
}

database {
  url = ${?DB_URL}
  driver = ${?DB_DRIVER}
  username = ${?DB_USERNAME}
  password = ${?DB_PASSWORD}
}

firebase {
  fcmCredentialPath = ${?FIREBASE_CREDENTIAL_PATH}
  projectId = ${?FIREBASE_PROJECT_ID}
}
