ktor:
  deployment:
    port: 8080
    host: "localhost"
  application:
    modules:
      - org.example.project.ApplicationKt.module
  environment: "dev"

database:
  url: "jdbc:postgresql://localhost:5432/srikandi"
  driver: "org.postgresql.Driver"
  username: "rebar"
  password: ""

firebase:
  fcmCredentialPath: "C:/dokumen/srikandi-app-firebase-adminsdk-fbsvc-a18ed7736a.json"