ktor:
  deployment:
    port: ${PORT:8080}
    host: ${HOST:localhost}
  application:
    modules:
      - org.example.project.ApplicationKt.module
  environment: ${ENV:dev}

database:
  url: ${DB_URL:jdbc:postgresql://localhost:5432/srikandi}
  driver: ${DB_DRIVER:org.postgresql.Driver}
  username: ${DB_USERNAME:rebar}
  password: ${DB_PASSWORD:}

firebase:
  fcmCredentialPath: ${FIREBASE_CREDENTIAL_PATH:C:/dokumen/srikandi-app-firebase-adminsdk-fbsvc-a18ed7736a.json}
  projectId: ${FIREBASE_PROJECT_ID:srikandi-app}